CREATE DATABASE Burger;
USE burger;

CREATE TABLE burgers (
id Int AUTO_INCREMENT NOT NULL PRIMARY KEY,
burger_name VARCHAR( 255) NOT NULL,
description VARCHAR( 255 ) NOT NULL,
devoured BOOLEAN,
date DATETIME DEFAULT CURRENT_TIMESTAMP
);

